using System;

namespace OCC.Shared.Models
{
    /// <summary>
    /// Represents a system user who can log in to the OCC Desktop or Mobile applications.
    /// Manages authentication credentials, profile data, and access permissions.
    /// </summary>
    /// <remarks>
    /// <b>Where:</b> Persisted in the <c>Users</c> table.
    /// <b>How:</b> Can be linked to an <see cref="Employee"/> record for HR purposes. 
    /// Access control is determined by <see cref="UserRole"/> and explicit <see cref="Permissions"/>.
    /// </remarks>
    public class User : BaseEntity
    {


        /// <summary> The user's login email address (must be unique). </summary>
        public string Email { get; set; } = string.Empty;

        /// <summary> The stored password hash (not plain text in production). </summary>
        public string Password { get; set; } = string.Empty; 

        /// <summary> User's first name. </summary>
        public string FirstName { get; set; } = string.Empty;

        /// <summary> User's surname. </summary>
        public string LastName { get; set; } = string.Empty;

        /// <summary> Contact telephone number. </summary>
        public string? Phone { get; set; }

        /// <summary> Physical location or office base. </summary>
        public string? Location { get; set; }

        /// <summary> Base64 encoded string of the user's profile image. </summary>
        public string? ProfilePictureBase64 { get; set; }

        /// <summary> The ID of the admin who approved this user's account registration. </summary>
        public Guid? ApproverId { get; set; }

        /// <summary> Flag indicating if the account has been approved by an admin. </summary>
        public bool IsApproved { get; set; } = false;

        /// <summary> Flag indicating if the email address has been confirmed. </summary>
        public bool IsEmailVerified { get; set; } = false;
        
        /// <summary> detailed permission string (e.g. JSON or delimited list) for fine-grained access. </summary>
        public string? Permissions { get; set; }
        
        /// <summary> Public RSA Key used for Client-Side Hybrid E2EE. </summary>
        public string? PublicKey { get; set; }
        
        /// <summary> Temporary Private Key generated by server for seamless onboarding (cleared once claimed). </summary>
        public string? ProvisionalPrivateKey { get; set; }
        
        /// <summary> The branch this user is primarily associated with (e.g. JHB or CPT). </summary>
        public Branch? Branch { get; set; }

        /// <summary> The high-level role group assigned to the user (e.g. Admin, SiteManager). </summary>
        public UserRole UserRole { get; set; } = UserRole.Guest;

        /// <summary> Helper property returning the full name in "FirstName, LastName" format. </summary>
        public string? DisplayName => (!string.IsNullOrWhiteSpace(FirstName) && !string.IsNullOrWhiteSpace(LastName)) 
            ? $"{FirstName}, {LastName}" 
            : $"{FirstName} {LastName}".Trim();
    }

    /// <summary>
    /// Defines broad access levels for system users.
    /// </summary>
    public enum UserRole
    {
        /// <summary> Full system access. </summary>
        Admin,
        /// <summary> Administrative and financial staff access. </summary>
        Office,
        /// <summary> Access limited to site management and project reporting. </summary>
        SiteManager,
        /// <summary> Third-party access (restricted). </summary>
        ExternalContractor,
        /// <summary> Health, Safety, Environment, and Quality access. </summary>
        HSEQ,
        /// <summary> Minimal read-only or pending access. </summary>
        Guest
    }
}
