using Microsoft.EntityFrameworkCore;
using OCC.Shared.Models;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;

namespace OCC.API.Data
{
    public class AppDbContext : DbContext
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        public AppDbContext(DbContextOptions<AppDbContext> options, IHttpContextAccessor httpContextAccessor = null!) : base(options)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        public DbSet<Project> Projects { get; set; }
        public DbSet<ProjectTask> ProjectTasks { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<TeamMember> TeamMembers { get; set; }

        public DbSet<TimeRecord> TimeRecords { get; set; }
        public DbSet<AttendanceRecord> AttendanceRecords { get; set; }
        public DbSet<LeaveRequest> LeaveRequests { get; set; }
        public DbSet<PublicHoliday> PublicHolidays { get; set; }
        public DbSet<OvertimeRequest> OvertimeRequests { get; set; }

        public DbSet<Notification> Notifications { get; set; }
        public DbSet<AppSetting> AppSettings { get; set; }
        public DbSet<TaskAssignment> TaskAssignments { get; set; }
        public DbSet<TaskComment> TaskComments { get; set; }
        public DbSet<AuditLog> AuditLogs { get; set; }

        public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
        {
            var auditEntries = OnBeforeSaveChanges();
            var result = await base.SaveChangesAsync(cancellationToken);
            await OnAfterSaveChanges(auditEntries);
            return result;
        }

        private List<AuditEntry> OnBeforeSaveChanges()
        {
            ChangeTracker.DetectChanges();
            var auditEntries = new List<AuditEntry>();
            foreach (var entry in ChangeTracker.Entries())
            {
                if (entry.Entity is AuditLog || entry.State == EntityState.Detached || entry.State == EntityState.Unchanged)
                    continue;

                var auditEntry = new AuditEntry(entry);
                auditEntry.TableName = entry.Entity.GetType().Name; // Simply use class name for now
                
                // Get User ID from Claims
                var userId = _httpContextAccessor?.HttpContext?.User?.FindFirst(ClaimTypes.Name)?.Value;
                auditEntry.UserId = userId ?? "System"; 

                auditEntries.Add(auditEntry);

                foreach (var property in entry.Properties)
                {
                    if (property.IsTemporary)
                    {
                        // value will be generated by the database, get the value after saving
                        auditEntry.TemporaryProperties.Add(property);
                        continue;
                    }

                    string propertyName = property.Metadata.Name;
                    if (property.Metadata.IsPrimaryKey())
                    {
                        auditEntry.KeyValues[propertyName] = property.CurrentValue;
                        continue;
                    }

                    switch (entry.State)
                    {
                        case EntityState.Added:
                            auditEntry.AuditType = "Create";
                            auditEntry.NewValues[propertyName] = property.CurrentValue;
                            break;

                        case EntityState.Deleted:
                            auditEntry.AuditType = "Delete";
                            auditEntry.OldValues[propertyName] = property.OriginalValue;
                            break;

                        case EntityState.Modified:
                            if (property.IsModified)
                            {
                                auditEntry.ChangedColumns.Add(propertyName);
                                auditEntry.AuditType = "Update";
                                auditEntry.OldValues[propertyName] = property.OriginalValue;
                                auditEntry.NewValues[propertyName] = property.CurrentValue;
                            }
                            break;
                    }
                }
            }

            // Save audit entities that have all the data we need
            foreach (var auditEntry in auditEntries.Where(_ => !_.HasTemporaryProperties))
            {
                AuditLogs.Add(auditEntry.ToAuditLog());
            }

            return auditEntries.Where(_ => _.HasTemporaryProperties).ToList();
        }

        private Task OnAfterSaveChanges(List<AuditEntry> auditEntries)
        {
            if (auditEntries == null || auditEntries.Count == 0)
                return Task.CompletedTask;

            foreach (var auditEntry in auditEntries)
            {
                // Get the final value of the temporary properties
                foreach (var prop in auditEntry.TemporaryProperties)
                {
                    if (prop.Metadata.IsPrimaryKey())
                    {
                        auditEntry.KeyValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                    else
                    {
                        auditEntry.NewValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                }

                // Save the AuditLog
                AuditLogs.Add(auditEntry.ToAuditLog());
            }

            return base.SaveChangesAsync();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // Configure relationships if needed
            // modelBuilder.Entity<ProjectTask>()
            //     .HasOne<Project>()
            //     .WithMany()
            //     .HasForeignKey(t => t.ProjectId);

            // Seed SA Public Holidays 2026
            modelBuilder.Entity<PublicHoliday>().HasData(
                new PublicHoliday { Id = Guid.NewGuid(), Date = new DateTime(2026, 1, 1), Name = "New Year's Day" },
                new PublicHoliday { Id = Guid.NewGuid(), Date = new DateTime(2026, 3, 21), Name = "Human Rights Day" },
                new PublicHoliday { Id = Guid.NewGuid(), Date = new DateTime(2026, 4, 3), Name = "Good Friday" },
                new PublicHoliday { Id = Guid.NewGuid(), Date = new DateTime(2026, 4, 6), Name = "Family Day" },
                new PublicHoliday { Id = Guid.NewGuid(), Date = new DateTime(2026, 4, 27), Name = "Freedom Day" },
                new PublicHoliday { Id = Guid.NewGuid(), Date = new DateTime(2026, 5, 1), Name = "Workers' Day" },
                new PublicHoliday { Id = Guid.NewGuid(), Date = new DateTime(2026, 6, 16), Name = "Youth Day" },
                new PublicHoliday { Id = Guid.NewGuid(), Date = new DateTime(2026, 8, 9), Name = "National Women's Day" },
                new PublicHoliday { Id = Guid.NewGuid(), Date = new DateTime(2026, 8, 10), Name = "Public Holiday" }, // Observed
                new PublicHoliday { Id = Guid.NewGuid(), Date = new DateTime(2026, 9, 24), Name = "Heritage Day" },
                new PublicHoliday { Id = Guid.NewGuid(), Date = new DateTime(2026, 12, 16), Name = "Day of Reconciliation" },
                new PublicHoliday { Id = Guid.NewGuid(), Date = new DateTime(2026, 12, 25), Name = "Christmas Day" },
                new PublicHoliday { Id = Guid.NewGuid(), Date = new DateTime(2026, 12, 26), Name = "Day of Goodwill" }
            );
        }
    }


    public class AuditEntry
    {
        public AuditEntry(Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry entry)
        {
            Entry = entry;
        }

        public Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry Entry { get; }
        public string UserId { get; set; } = string.Empty;
        public string TableName { get; set; } = string.Empty;
        public Dictionary<string, object?> KeyValues { get; } = new Dictionary<string, object?>();
        public Dictionary<string, object?> OldValues { get; } = new Dictionary<string, object?>();
        public Dictionary<string, object?> NewValues { get; } = new Dictionary<string, object?>();
        public List<Microsoft.EntityFrameworkCore.ChangeTracking.PropertyEntry> TemporaryProperties { get; } = new List<Microsoft.EntityFrameworkCore.ChangeTracking.PropertyEntry>();
        public List<string> ChangedColumns { get; } = new List<string>();
        public bool HasTemporaryProperties => TemporaryProperties.Any();
        public string AuditType { get; set; } = string.Empty;

        public AuditLog ToAuditLog()
        {
            var audit = new AuditLog();
            audit.UserId = UserId;
            audit.Action = AuditType; // Create, Update, Delete
            audit.TableName = TableName;
            audit.Timestamp = DateTime.UtcNow;
            audit.RecordId = System.Text.Json.JsonSerializer.Serialize(KeyValues);
            audit.OldValues = OldValues.Count == 0 ? null : System.Text.Json.JsonSerializer.Serialize(OldValues);
            audit.NewValues = NewValues.Count == 0 ? null : System.Text.Json.JsonSerializer.Serialize(NewValues);
            return audit;
        }
    }
}
